POST http://localhost:3000/api/stripe/create-customer
Content-Type: application/json

{
    "name": "Aoi Tanaka",
    "email": "test@gmail.com"
}

###
GET http://localhost:3000/api/stripe/fetch-products

###
POST http://localhost:3000/api/stripe/checkout